name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: hjk
            asset_name: hjk-linux-amd64
          - os: windows-latest
            artifact_name: hjk.exe
            asset_name: hjk-windows-amd64.exe
          - os: macos-13
            artifact_name: hjk
            asset_name: hjk-macos-amd64
          - os: macos-latest
            artifact_name: hjk
            asset_name: hjk-macos-arm
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          stack-no-global: true
          enable-stack: true
          stack-version: 'latest'
      - run: stack test
      - run: stack --local-bin-path target install
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
        if: ${{ startsWith(github.ref, 'refs/tags/') }}